[package]
name = "afk-av"
version = "0.1.0"
authors = ["kMeillet <kMeillet>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

enigo = "0.0.13"
rand = "0.7"
